version: '3'

services:
  web-app:
    image: emilyhuang19/web-app:latest
    container_name: web-app
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - /root/.env

  bar-recs:
    image: emilyhuang19/bar-recs:latest
    container_name: bar-recs-app
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - /root/.env

networks:
  app-network:
    driver: bridge
