version: '3.10'

services:
  webapp:
    build:
      context: .
      dockerfile: web-app/Dockerfile  # Ensure you are using the right Dockerfile
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DBNAME=${MONGO_DBNAME}
    depends_on:
      - mongo
      - bar_recs
    command: ["python", "app.py"]  # Change this if needed for the specific app entry point

  bar_recs:
    build:
      context: .
      dockerfile: bar_recs/Dockerfile  # Ensure you are using the right Dockerfile
    ports:
      - "5002:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DBNAME=${MONGO_DBNAME}
    depends_on:
      - mongo
    command: ["python", "bar_recs.py"]  # Change this if needed for the specific app entry point

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DBNAME}

volumes:
  mongo_data:
