name: CI/CD Pipeline for WebApp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: |
        # Build the Docker image
        docker build -t ${{ secrets.DOCKER_USERNAME }}/5-final-finalfour-webapp:latest ./web-app

    - name: Tag and Push the Docker image to Docker Hub
      run: |
        # Tag the Docker image with the latest tag
        docker tag 5-final-finalfour-webapp:latest ${{ secrets.DOCKER_USERNAME }}/5-final-finalfour-webapp:latest
        # Push the Docker image to Docker Hub
        docker push ${{ secrets.DOCKER_USERNAME }}/5-final-finalfour-webapp:latest

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.DO_IP }}
        username: root
        password: ${{ secrets.DO_PASSWORD }}
        script: |
          # SSH into your DigitalOcean droplet and deploy the app
          cd /path/to/your/project
          # Pull the latest Docker image from Docker Hub
          docker pull ${{ secrets.DOCKER_USERNAME }}/5-final-finalfour-webapp:latest
          # Stop the currently running container (if any)
          docker stop webapp || true
          # Remove the stopped container (if any)
          docker rm webapp || true
          # Run the new container
          docker run -d --name webapp -p 5001:5001 ${{ secrets.DOCKER_USERNAME }}/5-final-finalfour-webapp:latest
