name: CI/CD Pipeline for WebApp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/5-final-finalfour-webapp:latest .

    - name: Push the Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/5-final-finalfour-webapp:latest

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.DO_IP }}
        username: root
        password: ${{ secrets.DO_PASSWORD }}  # Store your password as a GitHub secret
        script: |
          cd /path/to/your/project
          docker pull ${{ secrets.DOCKER_USERNAME }}/5-final-finalfour-webapp:latest
          docker stop webapp || true
          docker rm webapp || true
          docker run -d --name webapp -p 5001:5001 ${{ secrets.DOCKER_USERNAME }}/5-final-finalfour-webapp:latest
