name: Build and Deploy

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/your-repo-name:latest .

    - name: Push the Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/your-repo-name:latest

    - name: Deploy to DigitalOcean
      run: |
        sudo apt-get install -y sshpass
        sshpass -p "${{ secrets.DO_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.DO_IP }} << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/your-repo-name:latest
          docker stop webapp || true
          docker rm webapp || true
          docker run -d --name webapp -p 5001:5001 ${{ secrets.DOCKER_USERNAME }}/your-repo-name:latest
        EOF
