version: '3.8'

services:
  web-app:
    image: emilyhuang19/web-app:latest
    container_name: web-app
    ports:
      - "5000:5000"  # Maps the container's port 5000 to the host's port 5000
    environment:
      - MONGO_DBNAME=finalfour
      - MONGO_URI=mongodb+srv://eh96:finalfour123@bars.ygsrg.mongodb.net/finalfour?tlsAllowInvalidCertificates=true
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_PORT=5000
      - FLASK_DEBUG=1
      - SECRET_KEY=this_is_my_random_secret_key_987654321
    restart: unless-stopped
    networks:
      - app-network

  bar-recs:
    image: emilyhuang19/bar-recs:latest
    container_name: bar-recs-app
    ports:
      - "5001:5001"  # Maps the container's port 5001 to the host's port 5001
    environment:
      - MONGO_DBNAME=finalfour
      - MONGO_URI=mongodb+srv://eh96:finalfour123@bars.ygsrg.mongodb.net/finalfour?tlsAllowInvalidCertificates=true
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_PORT=5001
      - FLASK_DEBUG=1
      - SECRET_KEY=this_is_my_random_secret_key_987654321
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
