name: CI/CD Pipeline for Web App

on:
  push:
    branches:
      - '**' 
  pull_request:
    branches:
      - '**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Python environment for linting
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies for linting
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Run pylint
      run: |
        pylint ./web_app/**/*.py || true

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push the Docker image
    - name: Build and push Docker image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/web_app:latest ./web_app --push

    # Deploy to DigitalOcean
    - name: Deploy to DigitalOcean
      with:
        host: ${{ secrets.DO_IP }}
        user: root
        docker pull ${{ secrets.DOCKER_USERNAME }}/bar_recs:latest
        docker stop bar_recs || true 
        docker rm bar_recs || true
        docker run -d --name bar_recs -p 5001:5001 --env-file /root/project/bar_recs/.env ${{ secrets.DOCKER_USERNAME }}/bar_recs:latest
